/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-col py-px w-full font-semibold bg-white max-md:mr-0.5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between px-20 py-16 leading-none bg-slate-500 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col items-start self-start mt-2.5 text-sm text-white">
          <div className="font-black">Tổ kỹ thuật / Technician</div>
          <div className="mt-2.5 leading-3 w-[275px]">
            <br /> Email : ddthu@hcmut.edu.vn
          </div>
          <div className="self-stretch mt-7">
            ĐT (Tel.) : (84-8) 38647256 - 5258
          </div>
        </div>
        <div className="flex flex-col text-base text-gray-100 min-h-[111px]">
          <div>Tải ứng dụng</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4878bac4a9b72ff5e56f0333ad7e512391c08fd43aa3c41fcc72378719cfe73a?placeholderIfAbsent=true&apiKey=985f1fb8be044ffd914af5aef5360e96"
            alt="Download app QR code"
            className="object-contain mt-5 max-w-full aspect-[3.38] w-[162px]"
          />
        </div>
      </div>
      <div className="pt-px pr-16 pb-10 pl-24 text-sm leading-3 text-white bg-sky-950 max-md:px-5 max-md:max-w-full">
        <br />
        <br />
        <span className="text-neutral-100">Copyright 2007-2024 BK-SPSS</span>
      </div>
    </footer>
  );
}

export default Footer;
