/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-col px-6 pt-4 pb-16 w-full bg-sky-50 max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col items-start pt-5 pl-14 bg-sky-200 max-md:pl-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/78e38272559179f95d3845b1ed840ba38465f2fefbd0fd3fad29c0c01697d288?placeholderIfAbsent=true&apiKey=985f1fb8be044ffd914af5aef5360e96"
          alt=""
          className="object-contain ml-10 aspect-[1.06] w-[54px] max-md:ml-2.5"
        />
        <div className="z-10 mt-0 ml-10 text-2xl tracking-tighter leading-none text-gray-800 max-md:ml-2.5">
          SPSS
        </div>
        <h1 className="z-10 self-stretch mt-0 mr-0 mb-0 text-3xl font-black text-center text-sky-200 border border-solid border-sky-950 leading-[50px] max-md:mb-2.5 max-md:max-w-full">
          Hệ thống máy in <br /> Trường Đại học Bách Khoa TP.Hồ Chí Minh
        </h1>
      </div>
    </header>
  );
}

export default Header;
