/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeaderMain from "../fragments/header/HeaderMain"
import Sidebar from "../fragments/slidebar/Sidebar";
import Footer from "../fragments/footer/Footer"

function Layout({ children }) {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <HeaderMain />
      <div className="max-md:mr-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <Sidebar />
          <main className="flex flex-col ml-5 w-[81%] max-md:ml-0 max-md:w-full">
            {children}
          </main>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default Layout;
