/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./BuyPaper/Layout";

function PrintingPage() {
  return (
    <Layout>
      <div className="flex flex-col mt-20 w-full max-md:mt-10 max-md:max-w-full">
        <div className="max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[41%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10">
                <div className="flex gap-5 w-2/3">
                  <label
                    htmlFor="paperType"
                    className="grow my-auto text-xl leading-snug text-black"
                  >
                    Loại giấy in:
                  </label>
                  <div className="flex flex-auto  whitespace-nowrap bg-white rounded-xl border border-black border-solid">
                    <select
                      id="paperType"
                      className=" ml-auto text-xl text-black bg-transparent rounded-xl border-none w-full"
                    >
                      <option>A4</option>
                    </select>
                  </div>
                </div>
                <div className="flex gap-10 mt-20 text-xl leading-snug text-black max-md:mt-10">
                  <label htmlFor="quantity" className="my-auto">
                    Số lượng:
                  </label>
                  <input
                    type="number"
                    id="quantity"
                    className="grow px-4 py-2 text-xl whitespace-nowrap bg-white rounded-xl border border-black border-solid w-fit max-md:pr-5"
                    defaultValue="100"
                  />
                </div>
                <label
                  htmlFor="totalAmount"
                  className="self-start mt-20 text-xl leading-snug text-black max-md:mt-10"
                >
                  Số tiền cần thanh toán
                </label>
                <input
                  type="text"
                  id="totalAmount"
                  className="px-2 pt-2.5 pb-2.5 mt-9 max-w-full text-xl leading-snug text-black bg-white rounded-xl border border-black border-solid w-[298px] max-md:pr-5"
                  value="150.000 VNĐ"
                  readOnly
                />
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[59%] max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0a3f32bd116ec870a5a0033720b078688ccb180bcad345877fab489633d1539a?placeholderIfAbsent=true&apiKey=985f1fb8be044ffd914af5aef5360e96"
                alt="Printing preview"
                className="object-contain grow w-full aspect-[1.69] max-md:mt-10 max-md:max-w-full"
              />
            </div>
          </div>
        </div>
        <button className="flex flex-col justify-center self-center px-16 py-6 mb-10 mt-56 max-w-full text-sm font-semibold tracking-wide leading-6 text-center text-white uppercase bg-blue-700 rounded-3xl w-[210px] max-md:px-5 max-md:mt-10">
          <div className="gap-2.5 self-stretch">XÁC NHẬN</div>
        </button>
      </div>
    </Layout>
  );
}

export default PrintingPage;
