/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex flex-col py-px mt-24 w-full bg-white max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between px-20 py-20 w-full leading-none bg-slate-500 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col items-start self-start mt-3 text-sm text-white">
          <h2 className="font-black">Tổ kỹ thuật / Technician</h2>
          <p className="mt-2.5 leading-3 w-[275px]">
            <br />
            Email : ddthu@hcmut.edu.vn
          </p>
          <p className="self-stretch mt-8">
            ĐT (Tel.) : (84-8) 38647256 - 5258
          </p>
        </div>
        <div className="flex flex-col text-base text-gray-100 min-h-[119px]">
          <p>Tải ứng dụng</p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9aa34f58536abcc82f4051df0cd6f9c8cc56484bc48d48e49f9926e5dd5a4b35?placeholderIfAbsent=true&apiKey=985f1fb8be044ffd914af5aef5360e96"
            alt="Download app"
            className="object-contain mt-5 max-w-full aspect-[3.38] w-[162px]"
          />
        </div>
      </div>
      <div className="pt-px pr-16 pb-11 pl-24 w-full text-sm leading-3 text-white bg-sky-950 max-md:px-5 max-md:max-w-full">
        <br />
        <br />
        <span className="text-neutral-100">Copyright 2007-2024 BK-SPSS</span>
      </div>
    </footer>
  );
}

export default Footer;
